# Generated by Django 3.1 on 2020-08-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
    ]
