# Generated by Django 3.1 on 2020-08-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200825_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
